<?php
	$_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
    $_attributes = $_product->getAttributes();
    
    $excludeArray = array();    
    
    foreach ($_attributes as $attribute)
    {
    	$attributeCode = $attribute->getAttributeCode();
		if ($attributeCode != 'tips')
		{
			$excludeArray[] = $attributeCode;
		}		
	}   
    
    if($_additional = $this->getAdditionalData($excludeArray))
    {
		foreach($_additional as $_data)
		{
			if ($_data['label'] == 'Tip')
			{
				echo '<div style="std">';				
				echo $_helper->productAttribute($_product, $_data['value'], $_data['code']);
				echo '</div>';
			}
		}	
	}
?>